source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target :TFTableViewManager do
##基础框架
pod 'TFTableViewManager', :path => '../'
pod 'SkeletonView'
end
